name: AutoBuild ERPNext Image

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches: [autobuild-enhancements]
    paths:
      - 'Dockerfile'
      - 'apps.json'
      - 'scripts/**'
      - '.github/workflows/autobuild.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest ERPNext Release Tag
        id: get_erpnext_tag
        run: |
          LATEST=$(curl -s https://api.github.com/repos/frappe/erpnext/releases/latest | jq -r .tag_name)
          echo "ERPNext_VERSION_TAG=$LATEST" >> $GITHUB_ENV
          echo "FRAPPE_BRANCH_FOR_BUILD=version-$(echo $LATEST | cut -d. -f1 | sed 's/v//')" >> $GITHUB_ENV
          echo "IMAGE_TAG_VERSION=$(echo $LATEST | sed 's/v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_ACCESS_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Log in to GitHub Container Registry
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker Tags
        id: prep_tags
        run: |
          TAG=${{ env.IMAGE_TAG_VERSION }}
          MAJOR=v$(echo $TAG | cut -d. -f1)
          IMAGE_DH=geniusdynamics/erpnext
          IMAGE_GH=ghcr.io/${{ github.repository_owner }}/erpnext
          TAGS="$IMAGE_DH:$TAG,$IMAGE_DH:$MAJOR,$IMAGE_GH:$TAG,$IMAGE_GH:$MAJOR"
          echo "FINAL_TAGS=${TAGS}" >> $GITHUB_ENV
          echo "BUILD_ARGS=--build-arg ERPNEXT_VERSION=${{ env.ERPNext_VERSION_TAG }} --build-arg FRAPPE_BRANCH=${{ env.FRAPPE_BRANCH_FOR_BUILD }}" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.FINAL_TAGS }}
          build-args: |
            ${{ env.BUILD_ARGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Summary
        run: |
          echo "✔️ Build completed for ERPNext ${{ env.ERPNext_VERSION_TAG }}"
          echo "Tags: ${{ env.FINAL_TAGS }}"
